### ISSUE TITLE
问一下，你有没有遇到electron-builder打包的时候，builder.build报错，我用了你的代码也是出现此问题

### ISSUE THREAD

**Issue by gluu1** [leibnizli/hummingbird#1]
执行到electron-builder的时候，报这样的错误……
builder.build(object.assign(cli.flags,{
    TypeError:undefined is not a function

))

**Comment by leibnizli** [comment]
可能是和版本有关吧，我当时的配置是可以的https://github.com/stormtea123/hummingbird/blob/master/package.json ，具体的我也记不清楚了，你自己摸索一下吧。
