### ISSUE TITLE
效果很好，也方便，可惜效率太低了

### ISSUE THREAD

**Issue by yoyoyosoro** [leibnizli/hummingbird#14]
大佬啥时候能升级一下啊，这CPU占用连20%都不到

**Comment by Yuanlailai** [comment]
是呀，效率有点低了，考虑到可以后台运行的原因，可以搞一个开关高速低速的。。不过支持！希望作者能做的更好！还有也就是整个文件夹的压缩，我觉得可能会有点工程量。

**Comment by leibnizli** [comment]
@Yuanlailai 整个文件夹的压缩已经支持了，请下载最新版😄

**Comment by leibnizli** [comment]
macOS v4.1.0 支持多线程压缩🎉
