### ISSUE TITLE
在文件较多的情况下无法正确进行处理

### ISSUE THREAD

**Issue by kafu0611** [leibnizli/hummingbird#16]
[img]https://i.imgur.com/18vDrJB.png[/img]
如图，因为是游戏贴图的文件所以文件非常多且杂，在压缩过程中往往跑到2~5%的时候就完全停住无法继续进行压缩了

另外也同样建议加入多线程支持，压缩的速度和占用有些不尽人意

**Comment by leibnizli** [comment]
你的文件太多了，如果有错误就跑不下去了

**Comment by kafu0611** [comment]
> 你的文件太多了，如果有错误就跑不下去了

如果是这样的话方便的话请添加一个遇到错误跳过该文件并导出相关log的功能？
可能会有点麻烦，但我个人认为在批量处理中如果遇到错误就停下来且无任何响应并不是一个较好的判定

**Comment by leibnizli** [comment]
嗯，暂时不想迭代，好耗费精力，你可以暂时先分开压缩看看到底哪个文件中断了。

**Comment by leibnizli** [comment]
@kafu0611 欢迎体验最新版
