### ISSUE TITLE
图片拖进去，没有压缩

### ISSUE THREAD

**Issue by DennisYu755** [leibnizli/hummingbird#17]
不知道为何，
我打开软件
拖入图片1~2MB左右
导出的图片没有任何压缩啊？

**Comment by leibnizli** [comment]
刚看见，如果是mac，下载最新版试一下

**Comment by catelina95** [comment]
就是下载的最新版没压缩没反应额

**Comment by thunkli** [comment]
前几天刚更新的，你反馈的是27天前

**Comment by leibnizli** [comment]
我又发布了一个最新版本4.0.0

**Comment by leibnizli** [comment]
@DennisYu755 @Sandural 如果图片质量已经很低就不会再压缩了，欢迎体验最新版本
