### ISSUE TITLE
不支持直接拖入文件夹，让人遗憾。

### ISSUE THREAD

**Issue by fantastlcok** [leibnizli/hummingbird#3]
希望能够识别直接拖入文件夹进行处理。
如果能有一个菜单让我选择是否备份原图就更好了，有些情况压完了不需要原图了。

**Comment by leibnizli** [comment]
@fantastlcok  感谢您的建议，有时间再迭代一下

**Comment by lijiaxiucai** [comment]
> 希望能够识别直接拖入文件夹进行处理。
> 如果能有一个菜单让我选择是否备份原图就更好了，有些情况压完了不需要原图了。

还是这个问题，要是有这方面的功能就更好了。

**Comment by leibnizli** [comment]
@fantastlcok @lijiaxiucai  整个文件夹的压缩已经支持了，请下载最新版😄
