### ISSUE TITLE
NW 打开,有进程,无界面

### ISSUE THREAD

**Issue by lzpong** [leibnizli/hummingbird#7]

**Comment by leibnizli** [comment]
@lzpong NW是什么鬼？

**Comment by lzpong** [comment]
nwjs,  你居然 不知道

**Comment by leibnizli** [comment]
兄弟，这个和nw没有关系

**Comment by lzpong** [comment]
electron太大了,  这个 都能 代替了(10M+) https://zhuanlan.zhihu.com/p/24426586 , https://github.com/weolar/miniblink49
