### ISSUE TITLE
拿了一堆jpg做测试，结果大小还变成原来的两倍，相当悲惨

### ISSUE THREAD

**Issue by oldmenplus** [leibnizli/hummingbird#8]
拿了一堆jpg做测试，结果大小还变成原来的两倍，相当悲惨，不压缩反而增加。

**Comment by leibnizli** [comment]
@oldmenplus  不可能吧，图片发过来我测试一下

**Comment by lwx5924** [comment]
好像是有这个问题

**Comment by yoyoyosoro** [comment]
github都会上，源的英文不认识？

**Comment by leibnizli** [comment]
@oldmenplus 如果图片质量已经非常低，再压缩就会变大，可以配置压缩质量，最低60

**Comment by oldmenplus** [comment]
> @oldmenplus 如果图片质量已经非常低，再压缩就会变大，可以配置压缩质量，最低60

(=^-ω-^=)    六年后.....
